import { QueryTypes } from "sequelize";
import { ApiError } from "@/lib/api-response";
import { sequelize } from "@/lib/sequelize";
import { tarjetasRepository } from "@/repositories/tarjetas.repository";
import { restarDinero } from "@/utils/decimal";
const money = (v) => /^\d+(\.\d{1,2})?$/.test(String(v)) && Number(v) > 0;

export const tarjetasService = {
  listar(usuarioId) { return tarjetasRepository.listar(usuarioId); },
  async detalle(usuarioId, id) { const [[tarjeta], consumos, pagos] = await tarjetasRepository.detalle(id, usuarioId); if (!tarjeta) throw new ApiError("Tarjeta no encontrada.",404); const usado=consumos.filter(c=>c.estado!=="ANULADO").reduce((x,c)=>x+Number(c.monto),0); const pagado=pagos.reduce((x,p)=>x+Number(p.monto),0); return { tarjeta, consumos, pagos, resumen:{ deuda:restarDinero(usado.toFixed(2),pagado.toFixed(2)), disponible:restarDinero(tarjeta.limite_credito,restarDinero(usado.toFixed(2),pagado.toFixed(2))) } }; },
  async crear(usuarioId,d) { if (!d.nombre?.trim()||!money(d.limiteCredito)||![d.diaCorte,d.diaPago].every(x=>Number.isInteger(Number(x))&&Number(x)>=1&&Number(x)<=31)|| (d.ultimosDigitos&&!/^\d{4}$/.test(d.ultimosDigitos))) throw new ApiError("Revisa los datos de la tarjeta.",422); const [moneda]=await sequelize.query("SELECT id FROM monedas WHERE id=:id AND activo=true",{replacements:{id:d.monedaId},type:QueryTypes.SELECT}); if(!moneda)throw new ApiError("Moneda inválida.",422); const [rows]=await sequelize.query("INSERT INTO tarjetas_credito(id,usuario_id,moneda_id,nombre,banco,ultimos_digitos,limite_credito,dia_corte,dia_pago,color) VALUES(gen_random_uuid(),:usuarioId,:monedaId,:nombre,:banco,:ultimos,:limite,:corte,:pago,:color) RETURNING *",{replacements:{usuarioId,monedaId:d.monedaId,nombre:d.nombre.trim(),banco:d.banco||null,ultimos:d.ultimosDigitos||null,limite:d.limiteCredito,corte:d.diaCorte,pago:d.diaPago,color:d.color||null},type:QueryTypes.INSERT});return rows[0]; },
  async actualizar(usuarioId,id,d) { const [rows]=await sequelize.query("UPDATE tarjetas_credito SET nombre=:nombre,banco=:banco,ultimos_digitos=:ultimos,dia_corte=:corte,dia_pago=:pago,color=:color,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND usuario_id=:usuarioId AND deleted_at IS NULL RETURNING *",{replacements:{id,usuarioId,nombre:d.nombre,banco:d.banco||null,ultimos:d.ultimosDigitos||null,corte:d.diaCorte,pago:d.diaPago,color:d.color||null},type:QueryTypes.UPDATE});if(!rows?.[0])throw new ApiError("Tarjeta no encontrada.",404);return rows[0]; },
  async consumo(usuarioId,d) { if(!money(d.monto)||Number(d.cantidadCuotas||1)<1)throw new ApiError("Monto o cuotas inválidos.",422); return sequelize.transaction(async transaction=>{const[card]=await tarjetasRepository.obtener(d.tarjetaId,usuarioId,transaction);if(!card?.activo)throw new ApiError("Tarjeta no encontrada o inactiva.",404);const[cat]=await sequelize.query("SELECT id FROM categorias WHERE id=:id AND activo=true AND (usuario_id=:usuarioId OR usuario_id IS NULL)",{replacements:{id:d.categoriaId,usuarioId},type:QueryTypes.SELECT,transaction});if(!cat)throw new ApiError("Categoría inválida.",422);const[rows]=await sequelize.query("INSERT INTO consumos_tarjeta(id,tarjeta_id,usuario_id,categoria_id,descripcion,monto,fecha,cantidad_cuotas,estado) VALUES(gen_random_uuid(),:tarjetaId,:usuarioId,:categoriaId,:descripcion,:monto,:fecha,:cuotas,'PENDIENTE') RETURNING *",{replacements:{tarjetaId:d.tarjetaId,usuarioId,categoriaId:d.categoriaId,descripcion:d.descripcion||null,monto:d.monto,fecha:d.fecha,cuotas:d.cantidadCuotas||1},type:QueryTypes.INSERT,transaction});return rows[0];}); },
  async pago(usuarioId,d) { if(!money(d.monto))throw new ApiError("Monto inválido.",422);return sequelize.transaction(async transaction=>{const[card]=await tarjetasRepository.obtener(d.tarjetaId,usuarioId,transaction);const[account]=await sequelize.query("SELECT id FROM cuentas WHERE id=:id AND usuario_id=:usuarioId AND moneda_id=:monedaId AND activo=true AND deleted_at IS NULL FOR UPDATE",{replacements:{id:d.cuentaId,usuarioId,monedaId:card?.moneda_id},type:QueryTypes.SELECT,transaction});if(!card||!account)throw new ApiError("Tarjeta o cuenta inválida.",422);const [tot]=await sequelize.query("SELECT COALESCE(SUM(monto) FILTER(WHERE estado<>'ANULADO'),0)::text consumos,COALESCE((SELECT SUM(monto) FROM pagos_tarjeta WHERE tarjeta_id=:id),0)::text pagos FROM consumos_tarjeta WHERE tarjeta_id=:id",{replacements:{id:d.tarjetaId},type:QueryTypes.SELECT,transaction});if(Number(d.monto)>Number(restarDinero(tot.consumos,tot.pagos)))throw new ApiError("El pago supera la deuda.",422);const[mrows]=await sequelize.query("INSERT INTO movimientos(id,usuario_id,cuenta_id,tipo,monto,fecha,descripcion,observaciones) VALUES(gen_random_uuid(),:usuarioId,:cuentaId,'AJUSTE',-:monto,:fecha,'Pago de tarjeta',:observacion) RETURNING *",{replacements:{usuarioId,cuentaId:d.cuentaId,monto:d.monto,fecha:d.fecha,observacion:d.observacion||null},type:QueryTypes.INSERT,transaction});const[prows]=await sequelize.query("INSERT INTO pagos_tarjeta(id,tarjeta_id,cuenta_id,usuario_id,monto,fecha,observacion,movimiento_id) VALUES(gen_random_uuid(),:tarjetaId,:cuentaId,:usuarioId,:monto,:fecha,:observacion,:movimientoId) RETURNING *",{replacements:{tarjetaId:d.tarjetaId,cuentaId:d.cuentaId,usuarioId,monto:d.monto,fecha:d.fecha,observacion:d.observacion||null,movimientoId:mrows[0].id},type:QueryTypes.INSERT,transaction});return {pago:prows[0],movimiento:mrows[0]};}); },
};
