"use client";

import { useEffect, useMemo, useState } from "react";
import { EmptyState, Loading } from "@/components/ui";
import { formatCurrency } from "@/utils/formatters";

const weekdays = ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"];
const months = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"];
const iso = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
function monthDays(cursor) { const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const start = new Date(first); start.setDate(first.getDate() - offset); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; }); }
function totals(events) { const result = {}; for (const event of events) { if (!event.moneda || !["INGRESO", "GASTO"].includes(event.tipo)) continue; const item = result[event.moneda] || { ingresos: 0, gastos: 0 }; if (event.tipo === "INGRESO") item.ingresos += Number(event.monto); else item.gastos += Number(event.monto); result[event.moneda] = item; } return result; }

export function CalendarioManager() {
  const [cursor, setCursor] = useState(() => new Date()); const [events, setEvents] = useState(null); const [error, setError] = useState("");
  const days = useMemo(() => monthDays(cursor), [cursor]);
  useEffect(() => { const timer = setTimeout(async () => { try { setEvents(null); const response = await fetch(`/api/calendario?desde=${iso(days[0])}&hasta=${iso(days.at(-1))}`); const data = await response.json(); if (!data.success) throw new Error(data.message); setEvents(data.data); } catch (err) { setError(err.message); setEvents([]); } }, 0); return () => clearTimeout(timer); }, [days]);
  const byDate = useMemo(() => { const map = new Map(); for (const event of events || []) { const list = map.get(event.fecha) || []; list.push(event); map.set(event.fecha, list); } return map; }, [events]);
  const move = (amount) => setCursor((value) => new Date(value.getFullYear(), value.getMonth() + amount, 1));
  const renderTotals = (daily) => Object.entries(totals(daily)).map(([currency, value]) => <div className="mt-1 grid grid-cols-2 gap-1 text-[11px]" key={currency}><span className="text-emerald-700">+ {formatCurrency(value.ingresos, currency)}</span><span className="text-red-700">− {formatCurrency(value.gastos, currency)}</span></div>);
  if (!events) return <Loading label="Cargando calendario" />;
  return <div className="space-y-5"><section className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-blue-800">Planificación</p><h1 className="text-3xl font-bold">Calendario financiero</h1></div><div className="flex gap-2"><button aria-label="Mes anterior" className="min-h-11 rounded-xl border px-4 font-bold" onClick={() => move(-1)} type="button">‹</button><button className="min-h-11 rounded-xl border px-3 text-sm font-semibold" onClick={() => setCursor(new Date())} type="button">Hoy</button><button aria-label="Mes siguiente" className="min-h-11 rounded-xl border px-4 font-bold" onClick={() => move(1)} type="button">›</button></div></section><h2 className="text-center text-lg font-bold capitalize">{months[cursor.getMonth()]} {cursor.getFullYear()}</h2>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="hidden overflow-hidden rounded-2xl border border-slate-200 bg-white md:block"><div className="grid grid-cols-7 border-b bg-slate-50">{weekdays.map((day) => <div className="p-3 text-center text-xs font-bold text-slate-500" key={day}>{day}</div>)}</div><div className="grid grid-cols-7">{days.map((day) => { const key = iso(day); const daily = byDate.get(key) || []; const current = day.getMonth() === cursor.getMonth(); return <article className={`min-h-32 border-b border-r p-2 ${current ? "bg-white" : "bg-slate-50 text-slate-400"}`} key={key}><p className="font-semibold">{day.getDate()}</p>{renderTotals(daily)}{daily.slice(0, 2).map((event, index) => <p className="mt-1 truncate text-[11px] text-slate-600" key={`${event.origen}-${index}`}>{event.descripcion || event.tipo}</p>)}{daily.length > 2 && <p className="text-[11px] text-blue-700">+{daily.length - 2} eventos</p>}</article>; })}</div></div><div className="space-y-3 md:hidden">{days.filter((day) => day.getMonth() === cursor.getMonth()).map((day) => { const daily = byDate.get(iso(day)) || []; return <article className="rounded-2xl border bg-white p-4" key={iso(day)}><div className="flex items-center justify-between"><h3 className="font-bold">{weekdays[(day.getDay() + 6) % 7]} {day.getDate()}</h3><span className="text-xs text-slate-500">{daily.length} eventos</span></div>{renderTotals(daily)}{daily.length ? <ul className="mt-3 space-y-1 text-sm">{daily.map((event, index) => <li className="truncate text-slate-600" key={`${event.origen}-${index}`}>{event.descripcion || event.tipo}</li>)}</ul> : <p className="mt-2 text-sm text-slate-400">Sin movimientos</p>}</article>; })}</div>{!events.length && <EmptyState title="Sin movimientos en este período" description="Los ingresos y gastos registrados aparecerán en sus fechas." />}</div>;
}
