"use client";
import { useEffect, useState } from "react";
import { Badge, Button, Card, EmptyState, Input, Loading, Modal, Select } from "@/components/ui";
import { formatCurrency } from "@/utils/formatters";

export function PresupuestosManager() {
  const [items, setItems] = useState(null); const [catalogos, setCatalogos] = useState({ categorias: [], monedas: [] }); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const [budget, accounts, movements] = await Promise.all([fetch("/api/presupuestos").then((r) => r.json()), fetch("/api/cuentas/catalogos").then((r) => r.json()), fetch("/api/movimientos/catalogos?tipo=GASTO").then((r) => r.json())]); if (budget.success) setItems(budget.data); else setMessage(budget.message); if (accounts.success && movements.success) setCatalogos({ monedas: accounts.data.monedas, categorias: movements.data.categorias }); }
  useEffect(() => { const timer = setTimeout(() => load().catch((error) => setMessage(error.message)), 0); return () => clearTimeout(timer); }, []);
  async function submit(event) { event.preventDefault(); setBusy(true); setMessage(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/presupuestos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); setBusy(false); if (!result.success) setMessage(result.message); else { setOpen(false); await load(); } }
  const tone = { NORMAL: "green", ADVERTENCIA: "amber", PELIGRO: "red" };
  return <div className="space-y-6"><section className="flex justify-between gap-4"><div><p className="text-sm font-semibold text-blue-800">Planificación</p><h1 className="mt-1 text-3xl font-bold">Presupuestos</h1><p className="mt-2 text-sm text-slate-600">Define límites semanales o mensuales por categoría.</p></div><Button onClick={() => setOpen(true)}>Nuevo presupuesto</Button></section>{message && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-800" role="alert">{message}</p>}{!items ? <Loading label="Cargando presupuestos" /> : items.length ? <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Card className="p-5" key={item.id}><div className="flex justify-between gap-3"><h2 className="font-bold">{item.categoria}</h2><Badge tone={tone[item.estado]}>{item.estado}</Badge></div><p className="mt-1 text-xs text-slate-500">{item.periodicidad === "SEMANAL" ? "Semanal" : "Mensual"}</p><p className="mt-3 text-2xl font-bold">{formatCurrency(item.gastado, item.moneda)}</p><p className="mt-1 text-sm text-slate-600">de {formatCurrency(item.montoPresupuestado, item.moneda)}</p><div className="mt-5 h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${item.estado === "PELIGRO" ? "bg-red-600" : item.estado === "ADVERTENCIA" ? "bg-amber-500" : "bg-emerald-600"}`} style={{ width: `${Math.min(100, item.porcentaje)}%` }} /></div><p className="mt-3 text-sm">Disponible: <strong>{formatCurrency(item.disponible, item.moneda)}</strong> · {item.porcentaje}%</p></Card>)}</section> : <EmptyState title="Aún no hay presupuestos" description="Crea un presupuesto semanal o mensual para vigilar tus gastos." />}<Modal isOpen={open} onClose={() => setOpen(false)} title="Nuevo presupuesto"><form className="space-y-4" onSubmit={submit}><Select label="Periodicidad" name="periodicidad" options={[{ value: "MENSUAL", label: "Mensual" }, { value: "SEMANAL", label: "Semanal (lunes a domingo)" }]} required /><Select label="Categoría de gasto" name="categoriaId" options={[{ value: "", label: "Selecciona una categoría" }, ...catalogos.categorias.map((c) => ({ value: c.id, label: c.nombre }))]} required /><Select label="Moneda" name="monedaId" options={[{ value: "", label: "Selecciona una moneda" }, ...catalogos.monedas.map((m) => ({ value: m.id, label: m.codigo }))]} required /><Input label="Monto presupuestado" name="montoPresupuestado" min="0.01" required step="0.01" type="number" /><Button type="submit" disabled={busy}>{busy ? "Guardando…" : "Guardar presupuesto"}</Button></form></Modal></div>;
}
