"use client";
import { useEffect, useState } from "react";
import { Badge, Button, Card, EmptyState, Loading, Modal } from "@/components/ui";
import { formatCurrency } from "@/utils/formatters";

const today = new Date().toISOString().slice(0, 10);
async function request(url, options) { const response = await fetch(url, options); const body = await response.json(); if (!body.success) throw new Error(body.message); return body.data; }

export function DeudasManager() {
  const [items, setItems] = useState(null); const [catalogos, setCatalogos] = useState({ monedas: [], cuentas: [] }); const [modal, setModal] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { const [deudas, cuentas, catalogs] = await Promise.all([request("/api/deudas"), request("/api/cuentas"), request("/api/cuentas/catalogos")]); setItems(deudas); setCatalogos({ monedas: catalogs.monedas, cuentas }); };
  useEffect(() => { const timer = setTimeout(() => { load().catch((e) => setError(e.message)); }, 0); return () => clearTimeout(timer); }, []);
  async function submit(event, url, method = "POST") { event.preventDefault(); setBusy(true); setError(""); try { await request(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); setModal(null); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  if (!items) return <Loading label="Cargando deudas" />;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-blue-800">Compromisos</p><h1 className="text-3xl font-bold">Deudas</h1></div><Button onClick={() => setModal({ type: "new" })}>Nueva deuda</Button></div>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p>}{items.length ? <div className="grid gap-4 md:grid-cols-2">{items.map((d) => <Card className="p-5" key={d.id}><div className="flex justify-between gap-2"><h2 className="font-bold">{d.persona_entidad}</h2><Badge>{d.estado}</Badge></div><p className="mt-1 text-sm">{d.tipo === "YO_DEBO" ? "Yo debo" : "Me deben"}</p><p className="mt-4 text-2xl font-bold">{formatCurrency(d.saldo_pendiente, d.moneda)}</p><p className="text-sm">Original {formatCurrency(d.monto_original, d.moneda)} · Pagado {formatCurrency(d.pagado, d.moneda)}</p><div className="mt-4 flex gap-2"><Button variant="secondary" onClick={() => setModal({ type: "pay", debt: d })} disabled={["PAGADO", "CANCELADO"].includes(d.estado)}>Registrar pago</Button><Button variant="danger" onClick={() => setModal({ type: "cancel", debt: d })} disabled={["PAGADO", "CANCELADO"].includes(d.estado)}>Cancelar</Button></div></Card>)}</div> : <EmptyState title="No hay deudas" description="Registra una deuda por pagar o cobrar." />}
    <Modal isOpen={modal?.type === "new"} title="Nueva deuda" onClose={() => setModal(null)}><form className="grid gap-3" onSubmit={(e) => submit(e, "/api/deudas")}><select name="tipo" defaultValue="YO_DEBO" className="min-h-11 rounded-xl border p-2"><option value="YO_DEBO">Yo debo</option><option value="ME_DEBEN">Me deben</option></select><input required name="personaEntidad" placeholder="Persona o entidad" className="min-h-11 rounded-xl border p-2"/><input name="descripcion" placeholder="Descripción" className="min-h-11 rounded-xl border p-2"/><input required min="0.01" step="0.01" name="montoOriginal" type="number" placeholder="Monto" className="min-h-11 rounded-xl border p-2"/><select required name="monedaId" className="min-h-11 rounded-xl border p-2">{catalogos.monedas.map((m) => <option key={m.id} value={m.id}>{m.codigo}</option>)}</select><input required name="fecha" type="date" defaultValue={today} className="min-h-11 rounded-xl border p-2"/><input name="fechaVencimiento" type="date" className="min-h-11 rounded-xl border p-2"/><input name="interes" min="0" step="0.0001" type="number" placeholder="Interés opcional" className="min-h-11 rounded-xl border p-2"/><Button type="submit" disabled={busy}>{busy ? "Guardando…" : "Crear deuda"}</Button></form></Modal>
    <Modal isOpen={modal?.type === "pay"} title="Registrar pago" onClose={() => setModal(null)}><form className="grid gap-3" onSubmit={(e) => submit(e, "/api/deudas/pagos")}><input type="hidden" name="deudaId" value={modal?.debt?.id || ""}/><input required name="monto" min="0.01" max={modal?.debt?.saldo_pendiente} step="0.01" type="number" placeholder="Monto" className="min-h-11 rounded-xl border p-2"/><select required name="cuentaId" className="min-h-11 rounded-xl border p-2">{catalogos.cuentas.filter((c) => c.monedaId === modal?.debt?.moneda_id).map((c) => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select><input required name="fecha" type="date" defaultValue={today} className="min-h-11 rounded-xl border p-2"/><input name="observacion" placeholder="Observación" className="min-h-11 rounded-xl border p-2"/><Button type="submit" disabled={busy}>Confirmar pago</Button></form></Modal>
    <Modal isOpen={modal?.type === "cancel"} title="Cancelar deuda" onClose={() => setModal(null)}><p className="mb-4">Esta acción no elimina el historial financiero.</p><Button variant="danger" disabled={busy} onClick={async () => { setBusy(true); try { await request(`/api/deudas/${modal.debt.id}/cancelar`, { method: "POST" }); setModal(null); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }}>Confirmar cancelación</Button></Modal>
  </div>;
}
