"use client";
import { useEffect, useState } from "react";
import { Button, Card, Input, Modal, Select } from "@/components/ui";

export function RecurrentesPanel({ catalogos }) {
  const [items, setItems] = useState([]); const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  async function load() { const result = await fetch("/api/recurrentes").then((r) => r.json()); if (result.success) setItems(result.data); }
  useEffect(() => { async function bootstrap() { const result = await fetch("/api/recurrentes").then((r) => r.json()); if (result.success) setItems(result.data); } bootstrap(); }, []);
  async function submit(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget).entries()); const result = await fetch("/api/recurrentes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }).then((r) => r.json()); if (!result.success) setMessage(result.message); else { setOpen(false); load(); } }
  async function process() { const result = await fetch("/api/recurrentes/procesar", { method: "POST" }).then((r) => r.json()); setMessage(result.success ? `${result.data.length} movimiento(s) generado(s).` : result.message); load(); }
  return <Card className="p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">Movimientos recurrentes</h2><p className="mt-1 text-sm text-slate-600">Automatiza ingresos y gastos programados.</p></div><div className="flex gap-2"><Button onClick={process} variant="secondary">Procesar pendientes</Button><Button onClick={() => setOpen(true)}>Configurar</Button></div></div>{message && <p className="mt-3 text-sm text-slate-700">{message}</p>}<div className="mt-4 space-y-2">{items.length ? items.slice(0, 5).map((item) => <div className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm" key={item.id}><span>{item.descripcion || item.tipo} · {item.frecuencia}</span><strong>{item.proximaEjecucion}</strong></div>) : <p className="text-sm text-slate-600">No hay recurrentes configurados.</p>}</div><Modal isOpen={open} onClose={() => setOpen(false)} title="Movimiento recurrente"><form className="space-y-3" onSubmit={submit}><Select label="Tipo" name="tipo" options={[{ value: "INGRESO", label: "Ingreso" }, { value: "GASTO", label: "Gasto" }]} /><Select label="Cuenta" name="cuentaId" options={[{ value: "", label: "Selecciona" }, ...catalogos.cuentas.map((item) => ({ value: item.id, label: item.nombre }))]} required /><Select label="Categoría" name="categoriaId" options={[{ value: "", label: "Selecciona" }, ...catalogos.categorias.map((item) => ({ value: item.id, label: item.nombre }))]} required /><Input label="Monto" name="monto" required step="0.01" type="number" /><Select label="Frecuencia" name="frecuencia" options={['DIARIO', 'SEMANAL', 'QUINCENAL', 'MENSUAL', 'ANUAL'].map((value) => ({ value, label: value }))} /><Input label="Fecha inicio" name="fechaInicio" required type="date" /><Input label="Fecha fin (opcional)" name="fechaFin" type="date" /><Input label="Descripción" name="descripcion" /><Button type="submit">Guardar</Button></form></Modal></Card>;
}
