import { Categoria } from "./Categoria";
import { Cuenta } from "./Cuenta";
import { EjecucionMovimientoRecurrente } from "./EjecucionMovimientoRecurrente";
import { Moneda } from "./Moneda";
import { Movimiento } from "./Movimiento";
import { MovimientoRecurrente } from "./MovimientoRecurrente";
import { Presupuesto } from "./Presupuesto";
import { TipoCambio } from "./TipoCambio";
import { TipoCuenta } from "./TipoCuenta";
import { Transferencia } from "./Transferencia";
import { Usuario } from "./Usuario";
import { MetaAhorro } from "./MetaAhorro";
import { AporteMeta } from "./AporteMeta";
import { ActivoPatrimonio } from "./ActivoPatrimonio";
import { ValoracionActivo } from "./ValoracionActivo";

if (Usuario && Moneda && TipoCuenta && Cuenta && Categoria && TipoCambio && Transferencia && Movimiento && Presupuesto && MovimientoRecurrente && EjecucionMovimientoRecurrente) {
  Usuario.hasMany(Cuenta, { foreignKey: "usuarioId", as: "cuentas" });
  Cuenta.belongsTo(Usuario, { foreignKey: "usuarioId", as: "usuario" });
  TipoCuenta.hasMany(Cuenta, { foreignKey: "tipoCuentaId", as: "cuentas" });
  Cuenta.belongsTo(TipoCuenta, { foreignKey: "tipoCuentaId", as: "tipoCuenta" });
  Moneda.hasMany(Cuenta, { foreignKey: "monedaId", as: "cuentas" });
  Cuenta.belongsTo(Moneda, { foreignKey: "monedaId", as: "moneda" });
  Usuario.hasMany(Categoria, { foreignKey: "usuarioId", as: "categorias" });
  Categoria.belongsTo(Usuario, { foreignKey: "usuarioId", as: "usuario" });
  Categoria.hasMany(Categoria, { foreignKey: "categoriaPadreId", as: "subcategorias" });
  Categoria.belongsTo(Categoria, { foreignKey: "categoriaPadreId", as: "categoriaPadre" });
  Moneda.hasMany(TipoCambio, { foreignKey: "monedaOrigenId", as: "tiposCambioOrigen" });
  Moneda.hasMany(TipoCambio, { foreignKey: "monedaDestinoId", as: "tiposCambioDestino" });
  TipoCambio.belongsTo(Moneda, { foreignKey: "monedaOrigenId", as: "monedaOrigen" });
  TipoCambio.belongsTo(Moneda, { foreignKey: "monedaDestinoId", as: "monedaDestino" });
  Usuario.hasMany(TipoCambio, { foreignKey: "usuarioId", as: "tiposCambio" });
  TipoCambio.belongsTo(Usuario, { foreignKey: "usuarioId", as: "usuario" });
  Transferencia.belongsTo(Cuenta, { foreignKey: "cuentaOrigenId", as: "cuentaOrigen" });
  Transferencia.belongsTo(Cuenta, { foreignKey: "cuentaDestinoId", as: "cuentaDestino" });
  Usuario.hasMany(Transferencia, { foreignKey: "usuarioId", as: "transferencias" });
  Usuario.hasMany(Movimiento, { foreignKey: "usuarioId", as: "movimientos" });
  Movimiento.belongsTo(Usuario, { foreignKey: "usuarioId", as: "usuario" });
  Cuenta.hasMany(Movimiento, { foreignKey: "cuentaId", as: "movimientos" });
  Movimiento.belongsTo(Cuenta, { foreignKey: "cuentaId", as: "cuenta" });
  Movimiento.belongsTo(Categoria, { foreignKey: "categoriaId", as: "categoria" });
  Movimiento.belongsTo(Transferencia, { foreignKey: "transferenciaId", as: "transferencia" });
  Transferencia.hasMany(Movimiento, { foreignKey: "transferenciaId", as: "movimientos" });
  Usuario.hasMany(Presupuesto, { foreignKey: "usuarioId", as: "presupuestos" });
  Presupuesto.belongsTo(Categoria, { foreignKey: "categoriaId", as: "categoria" });
  Presupuesto.belongsTo(Moneda, { foreignKey: "monedaId", as: "moneda" });
  Usuario.hasMany(MovimientoRecurrente, { foreignKey: "usuarioId", as: "movimientosRecurrentes" });
  MovimientoRecurrente.belongsTo(Cuenta, { foreignKey: "cuentaId", as: "cuenta" });
  MovimientoRecurrente.belongsTo(Categoria, { foreignKey: "categoriaId", as: "categoria" });
  MovimientoRecurrente.hasMany(Movimiento, { foreignKey: "movimientoRecurrenteId", as: "movimientos" });
  Movimiento.belongsTo(MovimientoRecurrente, { foreignKey: "movimientoRecurrenteId", as: "movimientoRecurrente" });
  MovimientoRecurrente.hasMany(EjecucionMovimientoRecurrente, { foreignKey: "movimientoRecurrenteId", as: "ejecuciones" });
  EjecucionMovimientoRecurrente.belongsTo(Movimiento, { foreignKey: "movimientoId", as: "movimiento" });
  Usuario.hasMany(MetaAhorro, { foreignKey: "usuarioId", as: "metas" });
  MetaAhorro.belongsTo(Moneda, { foreignKey: "monedaId", as: "moneda" });
  MetaAhorro.hasMany(AporteMeta, { foreignKey: "metaId", as: "aportes" });
  AporteMeta.belongsTo(Cuenta, { foreignKey: "cuentaId", as: "cuenta" });
  Usuario.hasMany(ActivoPatrimonio, { foreignKey: "usuarioId", as: "activosPatrimonio" });
  ActivoPatrimonio.belongsTo(Moneda, { foreignKey: "monedaId", as: "moneda" });
  ActivoPatrimonio.hasMany(ValoracionActivo, { foreignKey: "activoId", as: "valoraciones" });
}

export { ActivoPatrimonio, AporteMeta, Categoria, Cuenta, EjecucionMovimientoRecurrente, MetaAhorro, Moneda, Movimiento, MovimientoRecurrente, Presupuesto, TipoCambio, TipoCuenta, Transferencia, Usuario, ValoracionActivo };
